### ISSUE TITLE
The unresolved quotes check for search evaluates true for quotes inside the string

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx#271]
https://github.com/dag-hammarskjold-library/dlx/blob/b4f554c454449f23850941af53debd605fc033b6/dlx/marc/query.py#L44

e.g., if you are trying to save an auth heading `110 $aFoo "bar/baz" bay` the checking for quotes during tokenization ends up saying the quote is unresolved. This ultimately prevents such headings from being saved. 

@jbukhari

**Comment by aaronhelton** [comment]
https://github.com/dag-hammarskjold-library/dlx-rest/issues/1357

**Comment by jbukhari** [comment]
@aaronhelton I think this is/was an issue at the DLX-REST level
