### ISSUE TITLE
Return custom object from MARC.match() instead of a raw generator

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx#44]
Something like a pymongo cursor, that can have attributes such as 'count' that can be accessed without iterating through the generator

**Comment by grozdanic** [comment]
I was about to create an issue to have a function that will return an integer for search results counts. 
One concern, If you return a custom object here wouldn't you have to refactor the rest of the dlx ? Alternatively,  create just another function that will return a count for every compiled query. I was thinking maybe to create  decorator that would add .count() to the compiled query  ??

**Comment by jbukhari** [comment]
Refactoring shouldn't be necessary... the custom object could be an instance of a generator, so it would behave the same

**Comment by jbukhari** [comment]
closed by #53. MarcSet now handles batch operations.
